### PR TITLE
Add more sticks drop from leaves when broken by player

### PR DESCRIPTION
**Pull request by Insane96**
Since the sticks drop from leaves is reaaaally bad (2%) and it's pretty annoying to start, I've replaced the 16% chance for leaves to drop a stick when using a knife to a 16% chance for leaves to drop a stick when broken by the player.

I tried without the player condition, but you would get too many sticks when leaves decayed.

Due to me begin bad with git this PR contains the advancements changes too.

It's a draft as I need to test it.

### CODE REVIEW

**Comment by Insane96** [comment]
I'm not able to run data generators as I'm missing mods? I'm getting errors in data/integration/ModIntegration.

CHERRY_PLANKS is empty.

**Comment by wendall911** [comment]
Can you rework this one to not replace the drops with knife. That bonus drop for knife is intentional, and needs to stay. I don't mind having a little higher drop rate for punching leaves, but it shouldn't replace a mechanic that's been in the mod since the beginning. I merged your other branch with the advancements.

**Comment by wendall911** [comment]
I also changed the default branch. This can be done against 1.18.2 or 1.18.1 branch. I'll merge into both.

**Comment by Insane96** [comment]
Sure, still need to figure out how to runData.
Also maybe increase the knife drop to 20% and make the normal drop to 10%?

**Comment by wendall911** [comment]
Sorry, I'll provide some instructions for that. I had a weird workaround where I am using a script with a var that gets passed. It is called "datagen" in the main folder. Just use that script. Take a look, it just passes a var.

**Comment by wendall911** [comment]
Was my workaround for using datagen for the log recipes for other mods. It is a little hackish, and maybe there is a better way, but that's what I'm doing for now.

**Comment by wendall911** [comment]
Just one other comment. Don't replace imports with wild card imports. I understand your IDE probably does this, but I want all imports to be explicit.

**Comment by wendall911** [comment]
I haven't seen an update on this, so I think I'll add it, but will be sure to credit you in the commit.

**Comment by wendall911** [comment]
Have another bug fix going out soon, so want to add this as well.

**Comment by wendall911** [comment]
Ok, I added this commit: https://github.com/wendall911/TinkerSurvival/commit/5342e0d403f3d7747bb5bde15b1719395afed570

Also, released a new build with one of your other suggestions as well: https://www.curseforge.com/minecraft/mc-mods/tinkersurvival/files/3845581

**Comment by wendall911** [comment]
Also, let me know if you need this backported to 1.18.1. I only applied this to 1.18.2.

**Comment by Insane96** [comment]
Nah, I think think a really low percentage of people are playing 1.18.1.

Also wasn't able to run datagen so didn't keep going.

**Pull request closed without merging**
