### PR TITLE
Adds option to allow blocks to break again

### PR DESCRIPTION
**Pull request by ghost**
I added an option to allow empty hands and other tools to break blocks again. This is to allow players to break things like ice and glass with their fists, as well as stone and wood, which obviously still do not return a block.

### CODE REVIEW

**Comment by VinterNacht** [comment]
Before this gets merged, are you clever enough to add a config for blocks that are breakable by hand?  I've been hungering for this.

**Comment by ShadowBoxx-LLC** [comment]
I might be able to make that happen yeah. Let me see what I can figure out! Do you just want it to be a list of blocks that the mod will allow someone to break while not holding a tool?

If so... that would probably be pretty simple honestly.

**Comment by wendall911** [comment]
I'm out of town today, but will give this a look tomorrow. Thank you for the contribution! Let me know if you want to add anything. I can see the usefulness of this for some users, much appreciated.

**Comment by VinterNacht** [comment]
> I might be able to make that happen yeah. Let me see what I can figure out! Do you just want it to be a list of blocks that the mod will allow someone to break while not holding a tool?
> 
> If so... that would probably be pretty simple honestly.

Absolutely... With that ability I'd be able to give full integration with Underground Biomes, for instance.

**Comment by VinterNacht** [comment]
Any luck?

**Comment by wendall911** [comment]
@LunariusH Apologies for the very slow response on this. Summer is killing my off hours computer time. I'll take care of this today.

**Comment by VinterNacht** [comment]
I know I'm not entitled to this fix, but I'm excited to have it done! Thank you for your efforts!

**Comment by ShadowBoxx-LLC** [comment]
@LunariusH I haven't done anything for the blocks breakable by hand thing yet. I know exactly how to implement it, but like @wendall911 I have just been busy. I'll make it a separate PR as soon as I get it implemented.

I am also halfway through implementing some changes that allow you to configure which materials (aside from just wool and jellied slime, which are default) provide heat/cooling effects, as well as introducing and configuring possible modifier items that provide the same thing, if you have Tough As Nails and Construct's Armory installed.

I'll be doing both the breakable blocks by hand and the configurable materials and modifier items in separate PRs for @wendall911's sanity. 👍

**Comment by VinterNacht** [comment]
So was this completed and is waiting for merging?

**Comment by ShadowBoxx-LLC** [comment]
Yes, this is just waiting to be merged. I will add the other requested features in separate PRs if @wendall911 just wants to get this implemented right now.

**Comment by VinterNacht** [comment]
I actually found a way around it using CraftTweaker/ContentTweaker/etc... I removed Tinker's Survival, implemented all of its behaviors, and  kept compatibility with Underground Biomes through a series of scripts.  Thank you though!

**Comment by Terminal3D** [comment]
> I added an option to allow empty hands and other tools to break blocks again. This is to allow players to break things like ice and glass with their fists, as well as stone and wood, which obviously still do not return a block.

Hi, can u please explain, how u've compiled this mod after adding this feature? I just get this error:
Could not get unknown property 'keyStore' for root project 'tinkers survival' of type org.gradle.api.Project.

**Comment by ShadowBoxx-LLC** [comment]
> > I added an option to allow empty hands and other tools to break blocks again. This is to allow players to break things like ice and glass with their fists, as well as stone and wood, which obviously still do not return a block.
> 
> Hi, can u please explain, how u've compiled this mod after adding this feature? I just get this error: Could not get unknown property 'keyStore' for root project 'tinkers survival' of type org.gradle.api.Project.

It sounds like you don't have your forge environment set up correctly, or perhaps your dependencies are newer than they should be. This error means that it is missing something in the project itself. Basically the project 'tinkers survival' which is an object of type org.gradle.api.Project is missing a property called 'keyStore' that at a minimum your compiler expects to be present. Why that is the case I can't tell you.

**Pull request closed without merging**
